### ISSUE TITLE
Scratch Org source Tracking not working

### ISSUE THREAD

**Issue by jananijanarthanan** [dxatscale/sfpowerscripts#1050]
**Describe the bug**
After we create org pool with definition file setting of source tracking enabled, when we fetch the scratch from pool using orchestrator, is not creating any tracking files in the sfdx folder with the scratch org username 

**To Reproduce**
1. Create a scratch org dev pool with Source tracking enabled
2. fetch a scratch org the pool
3. There is no folder created  in the .sfdx folder inside the project

**Expected behavior**
The folder should be created with the necessary files inside .sfdx folder , in order for us to source pull our code updates into repository

Expected Files:
maxRevision.json
nonDecomposedElementsIndex.json
sourcePathInfos.json

**Screenshots**

<img width="254" alt="issue" src="https://user-images.githubusercontent.com/107583795/173921913-9163b320-84d1-492c-a973-da1b0be99637.png">

**Platform Details (please complete the following information):**
 - OS: Windows
 - Version [e.g. CLI Version  eg: 1.6.6] 
 - Salesforce CLI(sfdx cli) Version:7.1471
 - CI Platform: 

**Additional context**

**Comment by azlam-abdulsalam** [comment]
Hello @jananijanarthanan ,

Please refer to the issue here for details. https://github.com/dxatscale/sfpowerscripts/issues/817

Salesforce CLI has been updated with new source tracking which doesn't generate these files. You can also read the decision record here 

https://github.com/dxatscale/sfpowerscripts/blob/main/decision%20records/prepare/001-prepare-source-tracking.md

Can you provide details of sfpowerscripts version  and sfdx version? Also can you provide logs while using the fetch command 

Also have you tried a source push locally on a locally created scratch org and noticed any errors?

**Comment by jananijanarthanan** [comment]
Hi @azlam-abdulsalam , I am able to push code to my locally created scratch org, 

When I fetch a scratch org from the pool, I see the below error

Unable to update local source tracking due to fatal: reference is not a tree: 254283dedc0e53600b94a6dc659af496ae69c16c

On CLI version 7.147.1, 
@dxatscale/sfpowerscripts 13.6.22

**Comment by jananijanarthanan** [comment]
I have updated by CLI and sfpowerscripts to latest version , and the Source pull is working as expected. 
@dxatscale/sfpowerscripts 13.6.22
sfdx-cli/7.155.1 win32-x64 node-v16.13.0

**Comment by azlam-abdulsalam** [comment]
Closing this, as its working as expected
