### ISSUE TITLE
Scratch Org provisioning in pools fails because of ECONN... errors

### ISSUE THREAD

**Issue by domrycz** [dxatscale/sfpowerscripts#1144]
**Describe the bug**
Recently we had a lot of failed jobs which are creating scratch orgs in our pools. Not sure if it's sfpowerscripts or cli issue but this happens mostly when the long operation is performed (creating scratch orgs with many artifacts installed). It's barely happening when we create scratch org with dependencies (a few managed packages) only.

Examples of errors:

`Error: request to https://app-platform-3818.my.salesforce.com/services/Soap/m/56.0 failed, reason: connect ECONNREFUSED 35.158.154.83:443
Following Packages failed to deploy in SO1
[<names of packages here>]
Deployment of packages failed in SO1, this scratch org will be deleted`

`Error: The org cannot be found
Following Packages failed to deploy in SO1
[<names of packages here>]
Deployment of packages failed in SO1, this scratch org will be deleted`

`Error: Metadata API request failed: request to https://innovation-efficiency-3355.my.salesforce.com/services/data failed, reason: connect ECONNREFUSED 3.122.33.47:443
Following Packages failed to deploy in SO5
[<names of packages here>]
Deployment of packages failed in SO5, this scratch org will be deleted`

And this one during dependencies installation:
`Installing Package Dependencies of this repo in SO1
Failed to execute scripts for test-3d8d9bp34hko@example.com with alias SO1 due to {
  "status": 1,
  "name": "Fetch",
  "message": "request to https://enterprise-force-1253.scratch.my.salesforce.com/services/data/v56.0/tooling/sobjects/PackageInstallRequest/0Hf5r00000056BHCAY failed, reason: socket hang up",
  "exitCode": 1,
  "context": "PackageInstallCommand",
  "stack": "Fetch: request to https://enterprise-force-1253.scratch.my.salesforce.com/services/data/v56.0/tooling/sobjects/PackageInstallRequest/0Hf5r00000056BHCAY failed, reason: socket hang up\n    at Function.wrap (/usr/local/share/.config/yarn/global/node_modules/@salesforce/core/lib/sfError.js:84:25)\n    at PackageInstallCommand.catch (/usr/local/share/.config/yarn/global/node_modules/salesforce-alm/dist/ToolbeltCommand.js:255:44)\n    at async PackageInstallCommand._run (/usr/local/share/.config/yarn/global/node_modules/@salesforce/command/lib/sfdxCommand.js:106:13)\n    at async Config.runCommand (/usr/local/share/.config/yarn/global/node_modules/@oclif/core/lib/config/config.js:272:25)\n    at async run (/usr/local/share/.config/yarn/global/node_modules/@oclif/core/lib/main.js:76:5)\nCaused by: FetchError: request to https://enterprise-force-1253.scratch.my.salesforce.com/services/data/v56.0/tooling/sobjects/PackageInstallRequest/0Hf5r00000056BHCAY failed, reason: socket hang up\n    at ClientRequest.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/node-fetch/lib/index.js:1491:11)\n    at ClientRequest.emit (events.js:400:28)\n    at TLSSocket.socketOnEnd (_http_client.js:499:9)\n    at TLSSocket.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)",
  "warnings": [],
  "commandName": "PackageInstallCommand"
}
Succesfully deleted scratchorg  test-3d8d9bp34hko@example.com`

**To Reproduce**
Hard to reproduce, intermittent error which has intensified in recent days. Command used: sfpowerscripts:orchestrator:prepare

**Platform Details (please complete the following information):**
 - OS: Linux
 - sfpowerscripts 19.7.3

**Comment by domrycz** [comment]
FYI: @dieffrei @Chiqqn

**Comment by Janani-26** [comment]
I am also Consistently getting the below error in my prepare job

Failed to execute scripts for test-f2jfrenuzjid@example.com with alias SO1 due to {
  "status": 1,
  "name": "",
  "message": "The package version is not fully available. If this is a recently created package version, try again in a few minutes or contact the package publisher.",
  "exitCode": 1,
  "context": "PackageInstallCommand",
  "stack": "The package version is not fully available. If this is a recently created package version, try again in a few minutes or contact the package publisher.\n    at Function.wrap (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/sfError.js:61:25)\n    at PackageInstallCommand.catch (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/ToolbeltCommand.js:255:44)\n    at async PackageInstallCommand._run (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:93:13)\n    at async Config.runCommand (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:272:25)\n    at async run (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/main.js:76:5)",
  "warnings": [],
  "commandName": "PackageInstallCommand"
}

**Comment by azlam-abdulsalam** [comment]
Unable to reproduce, doesn't look something we could do
