### ISSUE TITLE
Bump jsforce

### ISSUE THREAD

**Issue by rygramer** [dxatscale/sfpowerscripts#1381]
I think this should be bumped to 2.0.0-beta.27. The current version of jsforce has a dependency to `xml2js` that is [vulnerable](https://security.snyk.io/package/npm/xml2js).
https://github.com/dxatscale/sfpowerscripts/blob/185b6fbcbd2d847619b021eaf48544506191cba2/packages/sfpowerscripts-cli/package.json#L33

**Comment by azlam-abdulsalam** [comment]
Thanks @rygramer  I don't think we can until sf migrates all other libs to use this, this is because the way we build in mono repo, last wee when i checked packaging lib was still on a version of @salesforce/core that is dependent on 19

I will have a check, that being said as most of these vulnerabilities are  on the context of a web application which serves incoming requests.

**Comment by rygramer** [comment]
Looks like `@salesforce/packaging (v2.3.1)` depends on [`@salesforce/core: ^4.3.10`](https://github.com/forcedotcom/packaging/blob/830d45bd52b80b09b7a5f96b9664961eee3ce7f1/package.json#L45)
And `@salesforce/core (v4.3.10)` depends on [`jsforce: ^2.0.0-beta.27`](https://www.npmjs.com/package/@salesforce/core/v/4.3.10?activeTab=code)

:) THANK YOU for all you do.

**Comment by azlam-abdulsalam** [comment]
awesome will update it straightaway
