### ISSUE TITLE
Apextests Slow during Parallel test in jenkins 

### ISSUE THREAD

**Issue by adarsha45** [dxatscale/sfpowerscripts#1399]
Currently, i am using this command to run particular apex test suite in jenkins parallel job , where  i am creating 'n' number of orgs based on  number of apex test suite available , and running each test suite in particualr job .

sfpowerscripts apextests:trigger -l RunApexTestSuite --apextestsuite CQControlledDocumentApexTestSuite -u ada-1
which have around 100 tests and is taking around 2 hours to complete when  running parallely , 
but when i run Runlocaltest which have around 1000 test,  is  taking only arounds 2 hours  
why is this happening?
and test are in queued state for around 30  minutes before starting any tests

**Comment by azlam-abdulsalam** [comment]
Hello @adarsha45 

- sfpowerscripts will attempt to run these tests in parallel in the org in the default mode,  So if the tests are not designed well, it will take more time due to the nature of these test waiting to get  locks on records.  You could try running the command in a sequential mode or set the behaviour in the org
- Regarding the queue,  it could be something that salesforce support could help,  probably a previous run was still running? From our perspective, we use the same apex library used by the sf cli

**Comment by azlam-abdulsalam** [comment]
@adarsha45  Any further comments? Please feel free to close the issue otherwise.  For general discussions you can join the community at https://launchpass.com/dxatscale

**Comment by adarsha45** [comment]
thanks , no further comments

**Comment by adarsha45** [comment]
thanks , no further comments
