### ISSUE TITLE
Error while running  :  sfpowerscripts apextests:trigger -l RunApexTestSuite  

### ISSUE THREAD

**Issue by adarsha45** [dxatscale/sfpowerscripts#1426]
even when all the test are passed i am getting this error causing the whole Jenkins build to fail .
-------------------------------------
Error: Test Execution failed
script returned exit code 1
--------------------------------------
and another issue being 
---------------------------------------------
System.DmlException: Insert failed. First exception on row 0; first error: UNKNOWN_EXCEPTION, common.udd.object.DmlOperationException: []
--------------------------------------
getting this issue in both 25.0.6 and 24.4.2

**Comment by azlam-abdulsalam** [comment]
Thanks for raising this issue, however I am closing this due to incomplete details, can you use the issue template here 

https://github.com/dxatscale/sfpowerscripts/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Also, please mention  in the issue, what is the error in the actual org, looking at the test run history
