### ISSUE TITLE
Instability with test coverage calculation

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#427]
**Describe the bug**

sfpowerscripts validate's package coverage feature for unlocked package is being reported to have random incorrect coverage reports

Need a consistent test coverage report.

**Comment by kknapp1** [comment]
@azlam-abdulsalam fwiw, this may not be an issue with sfpowerscripts. Since Spring '21 release, we've been having a lot of issues getting accurate code coverage reports on sandboxes and Production org too. Seems primarily an issue when running tests via sfdx cli or api. Works better when running tests in Dev Console or UI Test Execution.

Symptoms:
1. Tests run for over 24hours with no completion
2. Tests are ignored by the test runner, or not identified as test classes by the Developer tools (so the tests are ignored)
3. Code-coverage results are inconsistent likely due to incomplete tests runs or ignored tests

possible related issue: https://trailblazer.salesforce.com/issues_view?id=a1p4V000001SqnoQAC

**Comment by azlam-abdulsalam** [comment]
Closing this as its random, not an issue with packageTestCoverage calculation
