### ISSUE TITLE
Address potential breaking changes to apex tests

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#480]
Salesforce has published a blog detailing potential changes to the way reporting is done for apex tests. This might impact our classes on how read and manipulate coverage. This needs to be addressed once the CLI is updated

https://developer.salesforce.com/blogs/2021/04/clearer-apex-commands.html

**Comment by aly76** [comment]
There don't seem to be any compatibility issues from my initial assessment of the changes made by Salesforce. The formatting of the `test-result-codecoverage.json`, which we use to calculate code coverage, is unchanged. The only change is that
> the only classes listed in this file will be ones that are directly touched by the tests that were run.

which is fine since it's a reduction in data that we do anyways when filtering classes by package.

Salesforce is introducing a new `test-result-<testrunid>-codecoverage.json` that we could use to show the coverage coverage contribution of individual test methods.

**Comment by azlam-abdulsalam** [comment]
@aly76  can we close this ?

**Comment by aly76** [comment]
Prior assumption was wrong. Code coverage of classes from the package are overlooked if they are not **directly** touched by a test class.
