### ISSUE TITLE
Generate Changelog functionality only works for self hosted agents

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#514]
**Describe the bug**
The recently released release command which features the generate changelog functionality only works with self hosted agents and is not able to push the changes to cloud hosted agents

**To Reproduce**
1.  Create a release with --generatechangelog flag on a cloud hosted agent such as github action
2. Observe that the command fails to push

**Expected behavior**
The command should be able to push the changelog in all kinds of agents

https://github.com/dxatscale/easy-spaces-lwc/actions/runs/815791071

**Comment by aly76** [comment]
Solutions:

- User to setup SSH agent 
  - For hosted agents, look at action/ssh-agent
  - PRO: user may already need access to multiple private repo's and thus needs to setup SSH in order to get around GitHub actions limitation to the source repo 
  - CON: changelog does not work without SSH
  - CON: Higher-activation energy required from user

- Use the authenticated source repo instead of cloning a repo to tmp dir
  - Checkout the changelog branch & return to the original detached HEAD when done
    - Need to stash CWD before changing branches to avoid losing data 
    - CON?: the changelog repoURL is no longer a user-input, and must be the same as the source repo 
    - CON: `changelog:generate` is still dependent on SSH
    - CON: Compatibility must be maintained with this `changelog:generate` resulting in two control paths  
    - PRO: works without SSH
  - Copy the CWD to a tmp directory, which maintains auth to the source repo
    - PRO: free to modify tmp repo without having to revert to the original commit once done 
    - CON: Same as above
    
- Release ccommand can take GitHub token as a flag
  - Authenticate tmp dir using passed token 
  - CON: need to get auth token from CICD, which may not always be available?
  - CON: more work for the user
