### ISSUE TITLE
Test classes annotated with @isTest(seeAllData=false) are not parsed as a test class

### ISSUE THREAD

**Issue by jhawk-4** [dxatscale/sfpowerscripts#562]
**Describe the bug**
If a test class has a `seeAllData` descriptor with the annotation, it is not parsed as a test class for validation runs.

**To Reproduce**
Add a test class to a package and annotate it as `@isTest(seeAllData=false)`

**Expected behavior**
Test class should still be parsed and ran as part of the validation.

**Comment by azlam-abdulsalam** [comment]
@jhawk-4  Is this on 7.0.1 or latest alpha?

**Comment by azlam-abdulsalam** [comment]
@aly76 We have a similar issue impacting another implementation where test class was not detected. Not sure jts the same as @jhawk-4

**Comment by jhawk-4** [comment]
We are running 7.0.1 in our pipeline.

**Comment by azlam-abdulsalam** [comment]
@aly76  Can you look into this one and also check with @nawforce whether it has something to do with apex-parser

**Comment by nawforce** [comment]
@aly76 I think the problem is in https://github.com/Accenture/sfpowerscripts/blob/develop/packages/core/src/parser/listeners/ApexTypeListener.ts, it's testing 
`ctx._stop.text.toUpperCase() === "ISTEST"`
The context here the whole annotation so 'stop' will probably be ')' as the last token. There is a 'qualifiedName' child of annotation that should be good to compare against.

In theory qualified name could contain multiple identifiers separated by '.' . To save having to deal with this kind of detail I have a little helper function that creates a string for any parser context. Mine is in Scala but it's easy to construct since all parser context nodes support 'childCount' and 'getChild(i).text' so you can just write a loop to concat them to recover all the text used in any rule. I would probably use that on the 'qualifiedName'.

**Comment by aly76** [comment]
Some more context to this bug: it occurs when a class **only** contains isTest annotations with modifiers i.e. `@isTest(SeeAllData=true)` .

**Comment by aly76** [comment]
Found it simpler to just perform a string search on the annotation context's text field, than concatenating its children to rebuild the whole annotation.
