### ISSUE TITLE
Error validating against an Org and not finding commit ID

### ISSUE THREAD

**Issue by DanielCalle** [dxatscale/sfpowerscripts#754]
**Describe the bug**
When using validateAgainstOrg if the Commit Id is not found, an error is thrown and the pipeline stops

**To Reproduce**
Launch the Org validation without access to the commit or with the wrong commit ID set in the package of SfpowerscriptsArtifact__c record

**Expected behavior**
I think that if it cannot find the last commit the package was uploaded with, it should be deployed and save its commit ID. Stopping the execution is more painful than reinstalling the package.

**Screenshots**
![image](https://user-images.githubusercontent.com/11243437/140673757-b6cb2abe-a2f6-4f78-bf86-c341c6f48148.png)

**Platform Details (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version [e.g. CLI Version  eg: 1.6.6] 2.182.0
 - Salesforce CLI(sfdx cli) Version: 7.120.0
 - CI Platform:  Azure DevOps

**Comment by azlam-abdulsalam** [comment]
@DanielCalle  a fix is on the way, for more context, here is the discussion on this
https://github.com/Accenture/sfpowerscripts/discussions/713
You should remove sfpowerscripts artifact object as a workaround

**Comment by jhawk-4** [comment]
@azlam-abdulsalam I can understand the reasons why it is not ideal to do a diff check with org validation, however this significantly affected our pipeline run times after this was removed.  Would it be possible to accept this as a parameter in the `validateAgainstOrg` command so that users can choose if they want to do it or not?  Similar to to the build commands `--diffcheck`?  We're up to 7 packages in our pipeline and building them all caused us to start running into timeout issues in our pipeline as everything was deployed and validated.
